Updated RUN.md for Captura-Web
jokoframework/captura-formserver-community pull request #5
Opened 2024-04-19 20:31 UTC by Christian-Arce

New RUN.md

- Added necessary repositories for the project.
- Updated MongoDB and PostgreSQL configurations.
- Provided setup instructions for IntelliJ configuration
- Added Docker setup instruction
- Added permissions instruction for tomcat

2024-04-27 13:20 UTC, alefq commented on RUN.md
> +Navigate to the `captura-community-docker` folder and run the following command to set up Docker containers:
Agregar el enlace al repositorio.

2024-05-07 18:12 UTC, alefq requested changes

2024-05-07 18:12 UTC, alefq commented on RUN.md
> +Navigate to the `captura-community-docker` folder and run the following command to set up Docker containers:
@Christian-Arce esto falta completar

2024-05-07 18:51 UTC, Christian-Arce commented
Buenas tardes profesor, en el apartado de clone repositories se encuentra el enlace al community docker o preferiría que lo ponga ahí?  También el pull request de cipe lo hice en su repositorio personal.

2024-05-25 13:00 UTC, alefq approved these changes
Quedó mucho mejor. Buen trabajo. 💪🏽

2024-05-25 13:00 UTC, merged